#!/bin/sh
#
# @name Generic VTOL Tiltrotor
#
# @type VTOL Tiltrotor
#

. ${R}etc/init.d/rc.vtol_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=generic_tiltrotor_vtol}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1
param set-default SENS_EN_ARSPDSIM 1

# TODO: Enable motor failure detection when the
# VTOL no longer reports 0A for all ESCs in SITL
param set-default FD_ACT_EN 0
param set-default FD_ACT_MOT_TOUT 500

param set-default CA_AIRFRAME 3 # 机身类型，3 表示 Tiltrotor VTOL

param set-default COM_PREARM_MODE 2 # Prearm，间于Arm, Disarm之间的一种状态

param set-default SDLOG_MODE 0
# 电机参数
param set-default CA_ROTOR_COUNT 3
param set-default CA_ROTOR0_PX 1.0
param set-default CA_ROTOR0_PY -1.0
param set-default CA_ROTOR0_TILT 1
param set-default CA_ROTOR0_KM -0.05
param set-default CA_ROTOR1_PX 1.0
param set-default CA_ROTOR1_PY 1.0
param set-default CA_ROTOR1_TILT 2
param set-default CA_ROTOR2_PX -1.8

# 3个电机和4个舵机的输出
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 10
param set-default SIM_GZ_EC_MAX1 1500
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_MIN2 10
param set-default SIM_GZ_EC_MAX2 1500
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_MIN3 10
param set-default SIM_GZ_EC_MAX3 1500


param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_MIN1 0
param set-default SIM_GZ_SV_MAX1 1000
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_MIN2 0
param set-default SIM_GZ_SV_MAX2 1000
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_MIN3 0
param set-default SIM_GZ_SV_MAX3 1000
param set-default SIM_GZ_SV_FUNC4 204
param set-default SIM_GZ_SV_MIN4 0
param set-default SIM_GZ_SV_MAX4 1000
param set-default SIM_GZ_SV_FUNC5 205
param set-default SIM_GZ_SV_DIS5 200
param set-default SIM_GZ_SV_MIN5 0
param set-default SIM_GZ_SV_FUNC6 206
param set-default SIM_GZ_SV_DIS6 200
param set-default SIM_GZ_SV_MIN6 0

# 遥控器和空速管设置
param set-default COM_RC_IN_MODE 1
param set-default ASPD_PRIMARY 1

# 舵面参数设置
param set-default CA_SV_CS_COUNT 4 # 舵面数量
param set-default CA_SV_CS0_TYPE 1 # 1表示左副翼
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TYPE 2 # 2表示右副翼
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS2_TRQ_P 1
param set-default CA_SV_CS3_TYPE 4
param set-default CA_SV_CS3_TRQ_Y 1
param set-default CA_SV_TL_COUNT 2 # 倾转舵机总数

# 固定翼参数
param set-default NPFG_PERIOD 12
param set-default FW_AIRSPD_MIN 10.0
param set-default FW_AIRSPD_STALL 7.0

param set-default FW_PR_P 0.9
param set-default FW_PR_FF 0.5
param set-default FW_PR_I 0.5
param set-default TRIM_PITCH -0.15

param set-default FW_PSP_OFF 2
param set-default FW_P_LIM_MIN -15


param set-default FW_RR_FF 0.5
param set-default FW_RR_P 0.3
param set-default FW_RR_I 0.5

param set-default FW_YR_FF 0.5
param set-default FW_YR_P 0.6
param set-default FW_YR_I 0.5

param set-default FW_THR_MAX 0.6
param set-default FW_THR_MIN 0.05
param set-default FW_THR_TRIM 0.15

param set-default FW_T_CLMB_MAX 8
param set-default FW_T_SINK_MAX 2.7
param set-default FW_T_SINK_MIN 2.2

# 多旋翼参数
param set-default MC_AIRMODE 1
param set-default MC_PITCHRATE_I 0.3
param set-default MC_PITCHRATE_MAX 120.0
param set-default MC_PITCHRATE_P 0.25
param set-default MC_PITCH_P 4.5
param set-default MC_ROLLRATE_I 0.3
param set-default MC_ROLLRATE_P 0.28
param set-default MC_ROLL_P 4.0
param set-default MC_YAWRATE_I 0.4
param set-default MC_YAWRATE_P 0.6
param set-default MC_YAW_P 2.8
param set-default MC_YAWRATE_MAX 30


param set-default MIS_TAKEOFF_ALT 10 # 默认起飞高度

param set-default MPC_ACC_HOR_MAX 5.0
param set-default MPC_JERK_MAX 8.0
param set-default MPC_LAND_RC_HELP 1
param set-default MPC_THR_HOVER	0.7
param set-default MPC_VEL_MANUAL 8.0
param set-default MPC_VEL_MAN_SIDE 5.0
param set-default MPC_XY_CRUISE	6.0
param set-default MPC_XY_VEL_MAX 10.0

param set-default VT_FWD_THRUST_EN 4
param set-default VT_FWD_THRUST_SC 0.8
param set-default VT_FW_QC_P 70
param set-default VT_FW_QC_R 70
param set-default VT_TILT_TRANS	0.5
param set-default VT_TYPE 1
param set-default FD_ESCS_EN 0
